name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full history is fetched to check for changes

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Get package name from package.json
      id: package_name
      run: |
        PACKAGE_NAME=$(jq -r '.name' < package.json)
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

    - name: Get last published version from npm
      id: npm_version
      run: |
        echo "Fetching latest version for $PACKAGE_NAME"
        LAST_VERSION=$(npm show $PACKAGE_NAME version || echo "0.0.0")
        echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_ENV
        echo "Last published version: $LAST_VERSION"

    - name: Check if specific index changed
      id: file_changed
      run: |
        if git diff --name-only HEAD^ HEAD | grep 'index.ts'; then
          echo "File changed!"
          echo "CHANGE_TYPE=minor" >> $GITHUB_ENV
        else
          echo "File did not change"
          echo "CHANGE_TYPE=patch" >> $GITHUB_ENV
        fi

    - name: Bump version based on file change
      if: github.ref == 'refs/heads/main'
      run: |
        if [ "$CHANGE_TYPE" = "minor" ]; then
          echo "Bumping minor version..."
          NEW_VERSION=$(npx semver $LAST_VERSION -i minor)
        else
          echo "Bumping patch version..."
          NEW_VERSION=$(npx semver $LAST_VERSION -i patch)
        fi
        echo "New version to be published: $NEW_VERSION"
        npm version $NEW_VERSION --no-git-tag-version

    - name: Publish to npm
      if: github.ref == 'refs/heads/main'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
